package za.co.fleetexpense.enums;

public enum HandoffState {
    PENDING_HANDOFF_INITIATED,
    AWAITING_OLD_DRIVER_CONDITION,
    AWAITING_OLD_DRIVER_ODOMETER,
    AWAITING_MANAGER_APPROVAL,
    AWAITING_NEW_DRIVER_CONDITION,
    AWAITING_NEW_DRIVER_ODOMETER,
    HANDOFF_COMPLETE
}
